project:
  type: website
  output-dir: docs

website:
  title: "Flight Delays (FAA Data)"
  navbar:
    left:
      - text: "Overview"
        href: index.qmd
      - text: "About the Author"
        href: about.qmd
      - text: "Maximal Delays"
        href: maximal-delays.qmd
      - text: "Early Departures by Airline"
        href: maximal-early-departure.qmd
      - text: "Daily Flight Volume"
        href: flight-volume-by-day-of-week.qmd
      - text: "Worst Airports for Delays"
        href: worst-airports.qmd
      - text: "Why Is Your Flight Canceled?"
        href: flight-cancellations.qmd
      - text: "Moving Average Over Time"
        href: moving-average-flights.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

execute:
  echo: true
  warning: false
  message: false